export const countryCodeToNameMap: Record<string, string> = {
  POR: 'Portugal',
  ESP: 'Espanha',
  FRA: 'França',
  ENG: 'Inglaterra',
  SCO: 'Escócia',
  WAL: 'País de Gales',
  NIR: 'Irlanda do Norte',
  GER: 'Alemanha',
  ITA: 'Itália',
  NED: 'Países Baixos',
  BEL: 'Bélgica',
  SUI: 'Suíça',
  AUT: 'Áustria',
  DEN: 'Dinamarca',
  SWE: 'Suécia',
  NOR: 'Noruega',
  FIN: 'Finlândia',
  POL: 'Polónia',
  CZE: 'Chéquia',
  SVK: 'Eslováquia',
  HUN: 'Hungria',
  ROU: 'Roménia',
  ROM: 'Roménia',
  BUL: 'Bulgária',
  GRE: 'Grécia',
  TUR: 'Turquia',
  RUS: 'Rússia',
  UKR: 'Ucrânia',
  SRB: 'Sérvia',
  CRO: 'Croácia',
  BIH: 'Bósnia e Herzegovina',
  SVN: 'Eslovénia',
  MNE: 'Montenegro',
  ALB: 'Albânia',
  MKD: 'Macedónia do Norte',
  IRL: 'Irlanda',
  ISL: 'Islândia',
  ISR: 'Israel',
  USA: 'Estados Unidos',
  MEX: 'México',
  BRA: 'Brasil',
  ARG: 'Argentina',
  URU: 'Uruguai',
  CHI: 'Chile',
  COL: 'Colômbia',
  PER: 'Peru',
  ECU: 'Equador',
  VEN: 'Venezuela',
  BOL: 'Bolívia',
  PAR: 'Paraguai',
  JPN: 'Japão',
  KOR: 'Coreia do Sul',
  CHN: 'China',
  AUS: 'Austrália',
  NZL: 'Nova Zelândia',
  MAR: 'Marrocos',
  ALG: 'Argélia',
  TUN: 'Tunísia',
  EGY: 'Egito',
  RSA: 'África do Sul',
  NGA: 'Nigéria',
  CMR: 'Camarões',
  GHA: 'Gana',
  SEN: 'Senegal',
  CIV: 'Costa do Marfim',
  UCL: 'UEFA Champions League',
  UEL: 'UEFA Europa League',
  UECL: 'UEFA Conference League',
};

export const countryCodeToFlagMap: Record<string, string> = {
  POR: '🇵🇹',
  ESP: '🇪🇸',
  FRA: '🇫🇷',
  ENG: '\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}',
  SCO: '\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}',
  WAL: '🏴',
  NIR: '🇬🇧',
  GER: '🇩🇪',
  ITA: '🇮🇹',
  NED: '🇳🇱',
  BEL: '🇧🇪',
  SUI: '🇨🇭',
  AUT: '🇦🇹',
  DEN: '🇩🇰',
  SWE: '🇸🇪',
  NOR: '🇳🇴',
  FIN: '🇫🇮',
  POL: '🇵🇱',
  CZE: '🇨🇿',
  SVK: '🇸🇰',
  HUN: '🇭🇺',
  ROU: '🇷🇴',
  BUL: '🇧🇬',
  GRE: '🇬🇷',
  TUR: '🇹🇷',
  RUS: '🇷🇺',
  UKR: '🇺🇦',
  SRB: '🇷🇸',
  CRO: '🇭🇷',
  BIH: '🇧🇦',
  SVN: '🇸🇮',
  MNE: '🇲🇪',
  ALB: '🇦🇱',
  MKD: '🇲🇰',
  IRL: '🇮🇪',
  ISL: '🇮🇸',
  ISR: '🇮🇱',
  USA: '🇺🇸',
  MEX: '🇲🇽',
  BRA: '🇧🇷',
  ARG: '🇦🇷',
  URU: '🇺🇾',
  CHI: '🇨🇱',
  ROM: '🇷🇴',
  COL: '🇨🇴',
  PER: '🇵🇪',
  ECU: '🇪🇨',
  VEN: '🇻🇪',
  BOL: '🇧🇴',
  PAR: '🇵🇾',
  JPN: '🇯🇵',
  KOR: '🇰🇷',
  CHN: '🇨🇳',
  AUS: '🇦🇺',
  NZL: '🇳🇿',
  MAR: '🇲🇦',
  ALG: '🇩🇿',
  TUN: '🇹🇳',
  EGY: '🇪🇬',
  RSA: '🇿🇦',
  NGA: '🇳🇬',
  CMR: '🇨🇲',
  GHA: '🇬🇭',
  SEN: '🇸🇳',
  CIV: '🇨🇮',
  UCL: '🏆',
  UEL: '🏆',
  UECL: '🏆',
};
